### ISSUE TITLE
Ensure session ID is unique

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app#179]
We should find a way in Google Spreadsheet to prevent multiple sessions from sharing the same ID. Note that an ID cannot be reused once it has been assigned to a session (i.e., even if that session is later cancelled or deleted from the pool).

**Comment by mmmavis** [comment]
Maybe we don't need to care about old ID(ID that was assigned to a now removed session)  being used again. 

All we need to ensure is
- no multiple active sessions shares the same ID
- a session's ID cannot be modified once it's been assigned

@xmatthewx thoughts?

**Comment by xmatthewx** [comment]
It doesn't seem critical to worry about old IDs. Worst case: someone favorites a session that gets deleted and then replaced with a new session on the same idea. That person sees an incorrect favorite. Not ideal, not likely, not too terrible. 

This is one of the tradeoffs we make by using spreadsheets instead of a custom backend. I wouldn't worry about this.

**Comment by mmmavis** [comment]
This has been taken care of - through a semi-manual way.  There's a "ID Tracker" tab on the spreadsheet that lists ALL session IDs in the spreadsheet. Spreadsheet moderators will have to look for duplicates and resolve conflicts if there's any.
